### ISSUE TITLE
Deleting items when placing from offhand

### ISSUE THREAD

**Issue by Tmoemes** [ManatorDE/InvTweaks#1]
When placing blocks from your offhand while also having the same blocks in your inventory the item in your main hand will get deleted and replaced by the spares in your inventory. 
Video showing what's happening: [https://streamable.com/4gqixf](https://streamable.com/4gqixf)

**Comment by ManatorDE** [comment]
Thanks for reporting!
I'm working on fixing it!

**Comment by ManatorDE** [comment]
The bug was fixed and the update was just uploaded!
It might take some time to be available for download.

Just check every now and then on CurseForge/Bukkit!
